### ISSUE TITLE
has() function is not defined

### ISSUE THREAD

**Issue by f0vela** [leafsphp/session#1]
The documentation describes a has() method that doesn't exist in the session package, don't know if is an error on the docs or in the package itself.

I'm starting with leaf and tried to use this function, as described in the docs, to validate if the session variable exists and gave me an undefined method error.

<img width="444" alt="Screenshot 2023-12-07 at 10 42 16" src="https://github.com/leafsphp/session/assets/129066/bdc9584b-e88f-49b2-8787-06d57e0739ba">

<img width="1141" alt="Screenshot 2023-12-07 at 10 43 19" src="https://github.com/leafsphp/session/assets/129066/d5b1fccb-1e5d-42c7-adb7-a579c088b043">

**Comment by ibnsultan** [comment]
Run `composer update` to update your package, the issue has been fixed in the latest releas
